# Orbitron Deployment Configuration
# SodamFN Enterprise Management Platform
# Backend (FastAPI) + Admin Frontend (React) + Staff App (Cloudflare Pages)

project:
  name: sodam-fn
  region: ap-northeast-2  # Seoul

services:
  # ─────────────────────────────────────────────
  # Backend API (FastAPI + PostgreSQL)
  # ─────────────────────────────────────────────
  - name: sodam-backend
    type: web
    runtime: python
    rootDir: SodamApp/backend
    build:
      command: "pip install -r requirements.txt"
    start:
      command: "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    env:
      - key: DATABASE_URL
        from: database.sodam-db.connectionString
      - key: SECRET_KEY
        generate: true
      - key: FRONTEND_URL
        value: "https://sodamfn.twinverse.org"
      - key: STAFF_APP_URL
        value: "https://sodam-staff.pages.dev"
    healthCheck:
      path: /api/health
      interval: 30

  # ─────────────────────────────────────────────
  # Admin Frontend (Vite + React)
  # ─────────────────────────────────────────────
  - name: sodam-frontend
    type: static
    rootDir: SodamApp/frontend
    build:
      command: "npm install && npm run build"
    publish: ./dist
    env:
      - key: VITE_API_URL
        value: "https://sodamfn.twinverse.org"
      - key: VITE_STAFF_APP_URL
        value: "https://sodam-staff.pages.dev"
    routes:
      - source: "/*"
        rewrite: /index.html

# ─────────────────────────────────────────────
# Post-deploy: Staff App → Cloudflare Pages
# 재배포 시 자동으로 직원앱도 함께 빌드/배포
# ─────────────────────────────────────────────
postDeploy:
  - name: deploy-staff-app
    command: |
      cd SodamApp/staff-app
      npm install
      npm run build
      npx wrangler pages deploy dist --project-name sodam-staff --branch main
    env:
      - key: VITE_API_URL
        value: "https://sodamfn.twinverse.org"

databases:
  - name: sodam-db
    engine: postgres
    region: ap-northeast-2
    plan: starter
